version: "3.9"

services:
  redis:
    build:
      context: ./redis
      args:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - web

  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - web

  #php-fpm:
  #  build:
  #    context: ./php-fpm
  #    args:
  #      - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
  #  environment:
  #    - PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE}
  #    - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE}
  #    - PHP_XDEBUG_CLIENT_HOST=${PHP_XDEBUG_CLIENT_HOST}
  #    - PHP_XDEBUG_IDEKEY=${PHP_XDEBUG_IDEKEY}
  #  volumes:
  #    - ..:/home
  #  networks:
  #    - web

  #apache:
  #  build:
  #    context: ./apache
  #  environment:
  #    - TZ=${TZ}
  #  volumes:
  #    - ..:/home
  #  networks:
  #    web:
  #      aliases:
  #        - php.local
  #  ports:
  #    - 8080:80
  #    - 443:443
  #  depends_on:
  #    - php-fpm

  #nginx:
  #  build:
  #    context: ./nginx
  #  volumes:
  #    - ..:/home
  #  networks:
  #    web:
  #      aliases:
  #        - php.local
  #  ports:
  #    - 8080:80
  #    - 443:443
  #  depends_on:
  #    - php-fpm

  python:
    build:
      context: ./python
    volumes:
      - ..:/home
    networks:
      - web
    ports:
      - 8080:8080

  node:
    build:
      context: ./node
    volumes:
      - ..:/home
    networks:
      - web
    ports:
      - 8090:8090

volumes:
  redis-data:
  postgres-data:

networks:
  web:
